### ISSUE TITLE
As a customer/guest, I want to be able to navigate to checkout, so I can order the items in my shopping cart.

### ISSUE THREAD

**Issue by WILGROSS** [KYH-Net23/OrderProvider#1]
# Made by Mille Elfver, William Gross & Mousa Chammas

## **Acceptance Criterias**
- [x] Customers can interact with the checkout button when it has products in the cart.
- [x] If the cart is empty it cannot interact with the checkout button.
- [x] Pressing checkout navigates the user to the checkout page.

---

## **Activity Diagram**
[PlantUML Link](https://www.plantuml.com/plantuml/duml/POynReOm34RtdC9YWgaxBAYzGAyGWWaHYHt5JYLktpGTglvCjkJtR7-hg2rQKpIzCVD75UM4vSrN50NFAA0CSdBEWJouHYqc7EDduRqw5GZqVpg1daWmtYYJcT-hAXCSN61m9xgBgmvWzGU2ZLKvBO-hBWPt2NGUcW1Rt_84oNu5RxN_-8Slfa7PO1GSYQU79TW4Iu0fw_qQxLUbFHncRQMc-0q0)
![Image](https://github.com/user-attachments/assets/5d51c6ba-fd87-4815-863a-fa193099aed0)

---

## **Tasks**
- [x] KYH-Net23/Rika#53
> - [x] Add a checkout button on the bottom of the shopping cart card.

---

## **Test Case Descriptions**
- [x] Test case 1: Customer/guest clicks the checkout button.
- **Prerequisites**
  - Customer/guest has products in the shopping cart.
- **Steps:**

   - 1. Customer/guest goes to the shopping cart view.
   - 2. Customer/guest clicks the checkout button.
   - 3. Customer/guest gets navigated to order details.

- **Expected result:**
  - Customer is correctly navigated to order details.
