### ISSUE TITLE
As a customer/guest, I want to fill out the shipping/customer details form before I can navigate forward to the shipping options.

### ISSUE THREAD

**Issue by WILGROSS** [KYH-Net23/OrderProvider#10]
# Made by Mille Elfver, William Gross & Mousa Chammas

## **Acceptance Criterias**
- [x] Customer has navigated to the Order details page.
- [x] A form must be displayed for the customer to fill out their name, address details, phone number and email address.
- [x] Form must be correctly validated before the button to navigate to shipping options becomes clickable.

---

## **Activity Diagram**
[Plant UML Activity Diagram code](https://www.plantuml.com/plantuml/duml/PP2nJiD0343t-mgFxSJU3XGXPYJu0ZVdf9QSyybs8lBtk525WSsI_LvUxkA15iiivMSefzV5GsUofsaX3sYuyeH13g4bRWHgbGmg1R8uT9pe_0yQMNAdIy2T61xB7HhLvdFX4Gul8dbCKXtGybBDQ0ZPO4NXYa7r-NXtD3XivCToUcj1HdLN9LMmTs6g40fxO3PzthXtRXEyzs1j3jSbGbkvqf0rYQvfmAjaFuaJ79hc1pvIH6Pg4FGLm0wLlGjkL8isuFRNIByjZnz8Iwiy5W_jvP9plkat)
![Image](https://github.com/user-attachments/assets/5bf6a1da-7d00-4fcd-8b55-50e43f6d1e09)

---

## **Tasks**
 - [x] KYH-Net23/Rika#88
> - [x] Add a field for Given Name
> - [x] Add a field for Last Name
> - [x] Add a field for Street Address
> - [x] Add a field for Zip Code
> - [x] Add a field for City
> - [x] Add a field for Email
> - [x] Add a field for Phone Number
> - [x] Add a submit button

 - [x] #12
> - [x] Add Validation for Name Fields
> - [x] Add Regex validation for Email field
> - [x] Add relevant validation for all address detail fields

---

## **Test Case Descriptions**
- [x] **Test case 1: Detect empty entered Name Fields**
- **Prerequisites**
  - Access to the form on the order details page.
- **Steps:**
   - 1. Leave the "Given Name" AND “Last Name ”fields empty.
   - 2. Enter all other fields correctly.
   - 3. Try to submit the form
- **Expected result:**
  - The form should display red error texts above the name fields, indicating they are required.
  - The “Shipping Options” button should remain unavailable.

- [x] Test case 2: Detect incorrectly entered Name Fields
- **Prerequisites**
  - Access to the form on the order details page.
- **Steps:**
   - 1. Enter numbers and special characters into the "Given Name" and "Last Name fields.
   - 2. Enter all other fields correctly.
   - 3. Try to submit the form.
- **Expected result:**
  - The form should display red error texts above the name fields, indicating they are incorrectly entered.
  - The “Shipping Options” button should remain unavailable.

- [x] **Test case 3: Detect empty Email address field**
- **Prerequisites**
  - Access to the form on the order details page.
- **Steps:**
   - 1. Leave Email field empty
   - 2. Enter all other fields correctly.
   - 3. Try to submit the form.
- **Expected result:**
  - The form should display a red error text above the email field, indicating it’s required.
  - The “Shipping Options” button should remain unavailable.

- [x] **Test case 4: Detect incorrectly entered Email address field using RegEx**
- **Prerequisites**
  - Access to the form on the order details page.
- **Steps:**
   - 1. Enter an incorrect email address
   - 2. Enter all other fields correctly.
   - 3. Try to submit the form.
- **Expected result:**
  - The form should display a red error text above the email field, indicating it’s incorrectly entered.
  - The “Shipping Options” button should remain unavailable.

- [x] **Test case 5: Detect empty address fields**
- **Prerequisites**
  - Access to the form on the order details page.
- **Steps:**
   - 1. Leave the Street Address, Zip Code, and City fields empty
   - 2. Enter all other fields correctly.
   - 3. Try to submit the form.
- **Expected result:**
  -The form should display red error texts above the address fields, indicating they’re empty.
  - The “Shipping Options” button should remain unavailable.

- [x] **Test case 6: Detect incorrectly entered address fields**
- **Prerequisites**
  - Access to the form on the order details page.
- **Steps:**
   - 1. Enter special characters the Street Address, Zip Code, and City fields empty 
   - 2. Enter all other fields correctly.
   - 3. Try to submit the form.
- **Expected result:**
  -The form should display red error texts above the address fields, indicating they’re incorrectly entered.
  - The “Shipping Options” button should remain unavailable.

- [x] **Test case 7: Verify Error Message Display and Retention**
- **Prerequisites**
  - Access to the form on the order details page.
- **Steps:**
   - 1. Enter invalid data in all fields and submit.
   - 2. Correct one invalid field and submit again without correcting others.
   - 3. Correct all invalid fields and submit again.
- **Expected result:**
  - For step A, error messages should display on all fields with invalid input.
  - For step B, error messages should remain on the remaining invalid fields.
  - For step C, the form should submit successfully.
  - The “Shipping Options” button should become available once everything is correctly validated.

- [x] **Test case 8: Verify Successful Form Submission**
- **Prerequisites**
  - Access to the form on the order details page.
- **Steps:**
   - 1. Enter all fields correctly.
   - 2. Submit the form.
- **Expected result:**
  - No red error texts should be displayed on any fields.
  - The “Shipping Options” button should become available.
