### ISSUE TITLE
As an Admin, I want to be able to search for orders by Invoice-, Customer-, or Order-ID to quickly find an order or a list of orders.

### ISSUE THREAD

**Issue by acerd44** [KYH-Net23/OrderProvider#21]
**Made by Hossén & Oliver**
## Acceptance Criteria:
- [ ] The admin can input a search string to find specific invoices
- [ ] The admin can filter order depending on ID (order, customer or invoice ids).
- [ ] The admin can sort search results based on different fields.
- [ ] The admin can clear selected filters.
- [ ] The admin can apply pagination rules (results per page).
- [ ] The search results should update after every keystroke.
- [ ] If there are no results a special message should be displayed.

## Tasks:
- [ ] KYH-Net23/Rika#173
- [ ] KYH-Net23/Rika#174
- [ ] Implement a “Apply Filter” button.
- [ ] Implement a “Clear filters” button.
- [ ] Implement sorting buttons for fields: Customer ID, Invoice ID, Order ID and Status
- [ ] Implement a pagination button for choosing how many results should display per page.
- [ ] Implement an error message for when there are no search results.
