### ISSUE TITLE
As an Admin, I want to view a list of orders so that I can view and manage order information effectively

### ISSUE THREAD

**Issue by acerd44** [KYH-Net23/OrderProvider#22]
**Made by Hossén & Oliver**

## Acceptance Criteria
- [ ] Only admins should be able to view order information
- [ ] The page should show a list of all orders with relevant information
- [ ] Each order should have a link to view the order's details in another page.
- [ ] The page should have pagination.
- [ ] The page should have searching.
- [ ] The page should have sorting.
## Tasks
- [ ] Create an Order Data Model
   - Order Id 
   - Customer Id
   - Invoice Id
   - Date
   - List of products
   - Quantity
   - Price
   - Payment method
   - Delivery Address
   - Order Status
- [ ] Create an Order View Model
   - Order Id 
   - Customer Id
   - Invoice Id
   - Date
   - Price
- [ ] Implement API endpoint to retrieve a list of orders from the database.
- [ ] Implement authorization
- [ ] Implement searching
- [ ] Implement sorting
- [ ] Implement pagination
- [ ] Implement UI/frontend
  - [ ] Display the orders in a table
  - [ ] Implement button that links to the order's details page
## Test Cases
- [ ] Verify that the list of orders is loaded in correctly
  - Prerequisites: 
    - User is logged in as an Admin.
    - There is at least one order in the system.
  - Steps
    - Navigate to the orders list page.
  - Expected result: 
    - The page displays a list of orders in a table.
- [ ] Verify that only admins have access
  - Prerequisites: 
    - User is logged in as a customer or is not logged in.
  - Steps
    - Navigate to the orders list page (presumably by URL).
  - Expected result: 
    - Redirect the user to a 401 (unauthorized) page
    - Display error message saying “Not authorized to access this page"
- [ ] Verify that an error message is displayed when orders cannot be loaded
  - Prerequisites: 
    - User is logged in as an Admin.
    - There are either no orders or at least one order in the system.
  - Steps
    - Navigate to the orders list page.
  - Expected result: 
    - Display error message "Orders could not be fetched".
## Activity Diagram
![Image](https://i.imgur.com/mqx5Pfb.png)
