### ISSUE TITLE
As an admin, I want to view a detailed order page so that I can view all relevant information about a specific order

### ISSUE THREAD

**Issue by acerd44** [KYH-Net23/OrderProvider#23]
**Made by Hossén & Oliver**

## Acceptance Criteria
- [ ] Only admins should be able to access/view order information.
- [ ] Admin should be able to click on a ‘Details’ button tied on a specific order which redirects to the order's details page.
- [ ] The page should display relevant and correct information about the order.
## Tasks
- [ ] Create an Order Data Model
- [ ] Create an Order Details Model
- [ ] Implement API endpoint for fetching an order from the database
- [ ] Implement a method for mapping the order received from the database to return an Order Details model.
- [ ] KYH-Net23/AuthenticationService#1
- [ ] KYH-Net23/Rika#52
  - [ ] Display the information on the page.
## Test Cases
- [ ] Verify that the order details are loaded and displayed properly.
  - Prerequisites: 
    - User is logged in as an administrator.
    - User is navigated to either the ‘All Orders’ page or the ‘Order History’ page for a specific customer’s orders.
  - Steps
    - Click on the "Details" button of a specific order.
  - Expected result: 
    - The system displays the order information on the page.
- [ ] Verify that only admins can access and view order information.
  - Prerequisites:
    - The user attempting to access the page (presumably by URL) is not an administrator or is not logged in.
  - Steps:
      - Enter the URL for the customer's details page or the customer's order history page.
  - Expected results:
      - The user is redirected to a 401 error code page (unauthorized).
      - Display an error message.
- [ ] Verify that an error message is received when the order’s details could not be loaded correctly.
  - Prerequisites:
    - User is logged in as an administrator.
    - User is navigated to either the ‘All Orders’ page or the ‘Order History’ page for a specific customer’s orders.
  - Steps
    - Click on the "Details" button of a specific order.
  - Expected results:
    - The system displays an error message "Order details could not be loaded correctly".
## Activity Diagram
![Image](https://i.imgur.com/5PHsN4l.png)
