### ISSUE TITLE
As an admin, I want to be able to edit an order so that I can correct any mistakes

### ISSUE THREAD

**Issue by acerd44** [KYH-Net23/OrderProvider#30]
**Made by Hossén & Oliver**

## Acceptance Criteria
- [ ] Only admins should be able to access and view order information.
- [ ] There should be an “Edit Order” button on the order details page which enters Edit Mode.
- [ ] The admin should only be to modify specific details such as:
  - Products (add and remove)
  - Quantity of each product
  - Customer information (shipping address, contact details etc)
  - Order status
- [ ] There should be validation to prevent invalid entries.
- [ ] There should be "Save" and "Cancel" buttons
- [ ] There should be a confirmation prompt after pressing "Save" or "Cancel".
- [ ] Any changes should be logged.
## Tasks
- [ ] Implement API endpoint to update the order details.
- [ ] Implement authorization
- [ ] Implement validation
- [ ] Implement logging
- [ ] Implement UI/frontend
   - [ ] Implement a form for editing specific fields
   - [ ] Implement a "Save" button.
   - [ ] Implement a "Cancel" button.
   - [ ] Implement a prompt when pressing either of "Save" or "Cancel".
## Test Cases
- [ ] Verify that the admin can enter edit mode to update an order.
  - Prerequisites: 
    - The admin is logged in.
    - There is an existing order.
  - Steps
    - Navigate to the order's details page.
    - Click on the "Edit" button.
  - Expected result: 
    - The order page enters edit mode and fields are available to be changed.
- [ ] Verify that the admin can edit any of the editable fields and that it updates accordingly.
  - Prerequisites: 
    - The admin is logged in.
    - There is an existing order.
  - Steps
    - Navigate to the order's details page.
    - Click on the "Edit" button.
    - Change any of the fields (Add/delete items, change quantity etc)
    - Click "Save"
  - Expected result: 
    - The order details are updated accordingly and are displayed correctly.
- [ ] Verify that the "Cancel" button works properly and "resets" the order details to its default state.
  - Prerequisites: 
    - The admin is logged in.
    - There is an existing order.
  - Steps
    - Navigate to the order's details page.
    - Click on the "Edit" button.
    - Change any of the fields (Add/delete items, change quantity etc)
    - Click "Cancel"
  - Expected result: 
    - The order details have not been changed.
## Activity Diagram
![Image](https://i.imgur.com/4uwRRHg.png)
## Sequence Diagram
![Image](https://i.imgur.com/zrsLyOX.png)
