### ISSUE TITLE
As a customer/guest, I want to review my order details so that I can confirm all items and quantities.

### ISSUE THREAD

**Issue by WILGROSS** [KYH-Net23/OrderProvider#4]
# Made by Mille Elfver, William Gross & Mousa Chammas

## **Acceptance Criterias**
- [x] Customers/guests can click the checkout button.
- [x] Order details are shown on a new page.

---

## **Activity Diagram**
[PlantUML Link](https://www.plantuml.com/plantuml/duml/JSnB2i0m28JXlQVm7Cqcq9EaHcZ8mnBr_fMkkljXFYQhbMq-1tm1n-bgCdaZZKPTKHRIpTJ53IytavL-I9c3x1fPsKeRcY2c1pAl6gyl)
![Image](https://github.com/user-attachments/assets/64a66953-954a-4242-bb43-58312143a6d3)

---

## **Tasks**
- [x] KYH-Net23/Rika#63
> - [x] List of all products with their respective amounts, prices, total prices, and thumbnails.
> - [x] Add a Total Price calculation.
> - [x] Add Order Summary

---

## **Test Case Descriptions**
- [x] Test case 1: Correctly display order details
- **Prerequisites**
  - Customer/guest has products in the shopping cart.
- **Steps:**

   - 1. Customer/guest goes to the shopping cart view.
   - 2. Customer/guest clicks the checkout button.
   - 3. Customer/guest gets navigated to order details.

- **Expected result:**
  - Order details page with order summary, total price, discount codes and list of products with amounts, prices and thumbnails.
