### ISSUE TITLE
As a customer/guest I want to be able to view my shopping cart so that I can see products that I have added

### ISSUE THREAD

**Issue by Milles98** [KYH-Net23/OrderProvider#47]
# Made by Mille Elfver, William Gross & Mousa Chammas

## Acceptance Criterias
- [x] There must be a shopping cart button to the right in the navigation bar.
- [x] Clicking the button displays a fly-in/pop-up listing a summary of all products in the shopping cart.

---

## Activity Diagram
[PlantUML Activity Diagram Link](https://www.plantuml.com/plantuml/duml/VOr1QWCn34NtEiKdgyaYT9zi0kqDUW8pqNH4PLjOCiMthzFTGCdkWVJVktka5Zqh_G5Ttxj7pTomggpVZjFdNisaV66TznDahUL6ic4v720EpXRZZDYvO1diPxf-Y9kcWKt7HSgRLRjqUmuU25QTQvhlw3w34wJ1_xNUYDKPIwclfJyIEnAyvvpQeBeXgKA2iqFACt4CJ6zvo4OUrUW-kMVz1G00)
![Image](https://github.com/user-attachments/assets/8fa7e680-e9a3-43f8-b953-25894ae29e96)

---

## Sequence Diagram
[PlantUML Sequence Diagram Link](https://www.plantuml.com/plantuml/duml/XP3DQkim48NtUeh1gtiXfdk3IqXCYg4DQTCym5GHYQX-X3HgyTjNn5RiXk1kR6Rq7UjyNWP2Jr4hXfoiXtKCPBNmpAMrvDAX8IZsP-kSD2TOfosi8f4r1M2upFqu5pYqL_ZGpe5xuRya5rTwc7z76YJymD1JpOgnkePx1M6j9FyKHwXhbhMWV9nqhdhafaKnvDa8vjYXhQ2HmIdiOAEwKfg7dNLbTAm_pTpGkuAD87uUtABMw3l6K17il3r6JW6akPmo09WcquUIMWLFOi8-oz23pGhAsvlU14LlCZoo4sYqkCLpkPmOLF9V6wKl9j-IpcEhVrlKOW6jnbDwlKOq9AbR943oj7YtXEe_4oe8sDhxulCTYpkn0bv42Ed6FnlFfuKvicLwHAr-0000)
![Image](https://github.com/user-attachments/assets/9d33eba2-c8de-405e-8fc4-65e7b37a182d)

---

## Tasks
- [x] KYH-Net23/Rika#66
    - [x] Add a button to the navbar to open the shopping cart card.
- [x] KYH-Net23/Rika#58
    - [x] Add shopping cart information (products, amount, image, price and total price)

---

## Test Case Descriptions

- [x] Test case 1: Customer/guest views shopping cart with products added
- Prerequisites:
```
Products have been added to shopping cart.
```
- Steps:
```
1.  Customer/guest clicks the shopping cart button.
```
- Expected result:
```
Shopping cart fly-in/pop-up shows up with a summary of products added.
```
- [x] Test case 2: Customer/guest views shopping cart with no products in shopping cart
- Prerequisites:
```
No products have been added to the shopping cart.
```
- Steps:
```
1. Customer/guest clicks the shopping cart button.
```
- Expected result:
```
Shopping cart fly-in/pop-up shows up with the message “No products in shopping cart”.
```
