### ISSUE TITLE
As a customer/guest I want to be able to add items to my shopping cart, so that I can buy items

### ISSUE THREAD

**Issue by Milles98** [KYH-Net23/OrderProvider#48]
# Made by Mille Elfver, William Gross & Mousa Chammas

## Acceptance Criterias 

- [x] On each individual product page, there must be an “add to cart” button.
- [x] On each individual page, there must be an amount input next to the “add to cart” button.
- [x] Product must be added to the shopping cart after the button is pressed.
- [x] Must show confirmation that the product is added to cart with anything green. 
- [x] Shopping cart icon is updated to display the quantity of products added.

---

## Activity Diagram
[PlantUML Activity Diagram Link](https://www.plantuml.com/plantuml/uml/POv1RW8n34NtEON52gx0RAYuGAMUm1rxm6fYfx7JYjkN81Y1kaeiF___3XxOefUSRf-qFtOFAzpWH_ZN0I6B1zW2jHdrENnAicnN2eaSmc36TgNqGLrV7W4xY3ChR2_ikyJP6RPgkvSMb_3rZ3XGydN64qzFs8mAehK7OB6kpq8lM9Rvos7pHZIaZjXY0vyzmdHAh2HBsh_VgyI7FDFTVkHydArMqTDj7a2lXC4qAamNQGL3JA6mEvvu42HUCrwO_f_Ffe_rcWJV7JKaBbFoi9eEhDHB_WC0)
![Image](https://github.com/user-attachments/assets/ba570458-b931-4f25-89bf-3e9bfb240dc9)

---

## Tasks
- [x] KYH-Net23/Rika#60
  - [x] Create an “Add to Cart” button for the individual product page.
- [x] KYH-Net23/Rika#61
  - [x] Add a + icon to increase the desired amount in increments.
  - [x] Add a - icon to decrease the desired amount in increments. (No lower than 1)
- [x] KYH-Net23/Rika#62
  - [x] Green box with confirmation message.
- [x] KYH-Net23/OrderProvider#56
  - [x] Add cookies or local storage to save items to shopping cart
- [x] KYH-Net23/OrderProvider#53
  - [x] Write unit tests to ensure functionality is working correctly, write integration tests to ensure it cooperates with other system

---

## Test Case Descriptions

- [x] Test case 1: Product is added to shopping cart
- Prerequisites:
```
Customer/guest is viewing a list of products or a specific product.
```
- Steps:
```
1. Customer/guest clicks the “add to cart” button on a product.
```
- Expected result:
```
Product is added to cart.
```
