### ISSUE TITLE
As a customer/guest I want to be able to edit products in my shopping cart so that I can change their amounts.

### ISSUE THREAD

**Issue by Milles98** [KYH-Net23/OrderProvider#49]
# Made by Mille Elfver, William Gross & Mousa Chammas

## Acceptance Criterias

- [x] Customers//guests can click on the “+” button to increase the quantity of the product.
- [x] Customers/guests can click on the “-” button to decrease the quantity of the product.
- [x] Customers/guests can type a number in the input field to change the quantity of the product.

---

## Activity Diagram
[PlantUML Activity Diagram Link](https://www.plantuml.com/plantuml/duml/XP2nRaCX34LtlkAEoPYrRsYa_a2bVW41arW1Wx19bRylIOQ-fmvT49AlZw_EKSrt6oMxvyUzVGorMgZZnlIjq4jjZUMCCAVGKOhlzyMbsg-hB8bHLzTwZICOVAb3pB70BWIMDWo9ASVN8lpPipZW5n0oX-i4vA4u3RCgosF-kG62TJ939wyKSRhZy0yFXMK3v8JT7oOEx_j7KS7kJhftmEhoFDcfr1j5f5xBKyE3H5a9EwdR-Afef6rHW2HoSlF5ozxNHYqhHelUA2uhiPq2yOqKeKhYNhnn5HHIzMTQt4mrTvp8KV8F)
![Image](https://github.com/user-attachments/assets/010e5d15-3aa5-4af5-8500-7631b3a3031c)

---

## Tasks
- [x] KYH-Net23/Rika#70
  - [x] Button decreases product quantity in shopping cart.
  - [x] If quantity is 1 the product gets removed.
- [x] KYH-Net23/Rika#71
  - [x] Button increments product quantity in shopping cart.
- [x] KYH-Net23/Rika#72
  - [x] Input field allows the user to choose quantity freely.

---

## Test Case Descriptions
- [x] Test case 1: Customer/guest clicks “-” in shopping cart for a product with more than 1 in quantity
- Prerequisites:
```
A product is in the shopping cart.
Product quantity in the shopping cart is 4.
```
- Steps:
```
1. Customer/guest clicks “-” button.
```
- Expected result:
```
Amount is decreased to 3 (in increments of 1).
```

- [x] Test case 2: Customer/guest clicks “-” in shopping cart for a product with 1 in quantity
- Prerequisites:
```
A product is in the shopping cart.
Product quantity in shopping cart is 1.
```
- Steps:
```
1. Customer/guest clicks “-” button.
```
- Expected result:
```
Product is removed from the shopping cart.
```

- [x] Test case 3: Customer/guest clicks “+” in shopping cart for a product with 1 in quantity
- Prerequisites:
```
A product is in the shopping cart.
Product quantity in shopping cart is 1.
```
- Steps:
```
1. Customer/guest clicks the “+” button.
```
- Expected result:
```
Amount is increased to 2.
```

- [x] Test case 4: Customer/guest types a number in shopping cart input field for products
- Prerequisites:
```
A product is in the shopping cart.
```
- Steps:
```
1. Customer/guest types “5” in the input field.
```
- Expected result:
```
Amount is changed to 5.
```
