### ISSUE TITLE
As a customer/guest I want to be able to remove products from my shopping cart if I don’t want it anymore.

### ISSUE THREAD

**Issue by Milles98** [KYH-Net23/OrderProvider#50]
# Made by Mille Elfver, William Gross & Mousa Chammas

## Acceptance Criterias

- [x] Customers/guests can click the shopping cart icon to view the shopping cart summary card.
- [x] Customers/guests can click on the trash icon button or “-” button.
- [x] Product gets removed from cart.
- [x] Shopping cart summary card is updated.

---

## Activity Diagram
[PlantUML Activity Diagram Link](https://www.plantuml.com/plantuml/duml/XT0nRiCm30NGNQVuepDcZOS6Q0zGe2TWPDecOaakIRdmxUkuAT821Re86ZwVn7ys9_MQfh1VmkcvcfV4YaNums1ZcMV90oAfmsfAf6iR-gBN03pISP9uDRYIZRXKzvBRM-1LIrUZGmpAgIpSeTUITkwB0Gqa-IyiIQxs0vCUpRT7gTIyiyUd0tpaZ6PbEmJWtrS1depHv7AFlt1K9cFCzxdtIjd5LrnM7FU1t4aVjXFxve-lAaUMXGsnv5uqaKl9I6n60xVXzFQhFp7KkIFdhWqRC8VpHjxA_mG0)
![Image](https://github.com/user-attachments/assets/a0d76394-d852-432e-8ce2-3bc4dfd11e2d)

---

## Tasks
- [x] KYH-Net23/Rika#67
  - [x] Button removes the whole product quantity of a specific product in the shopping cart.
- [x] KYH-Net23/Rika#68
  - [x] Button removes the product in the shopping cart if the quantity is 1.

---

## Test Case Descriptions
- [x] Test case 1: Product is removed from shopping cart through trash can button
- Prerequisites:
```
Customers/guests have opened the shopping cart summary card.
There is a product added to the shopping cart.
```
- Steps:
```
1. Customer/guest clicks the “trash can” button on a product.
```
- Expected result:
```
Product is removed from cart.
Confirmation message is displayed.
```

- [x] Test case 2: Product is removed from shopping cart through “minus” button
- Prerequisites:
```
Customer/guest has opened the shopping cart summary card.
There is a product added to the shopping cart.
Product amount is 1.
```
- Steps:
```
1. Customer/guest clicks the “-” button on a product.
```
- Expected result:
```
Product is removed from cart.
Confirmation message is displayed.
```
