### ISSUE TITLE
As a customer I want to save my shopping cart items when I leave the page so that I can come back later to complete my purchase without losing my selected items.

### ISSUE THREAD

**Issue by Milles98** [KYH-Net23/OrderProvider#51]
# Made by Mille Elfver, William Gross & Mousa Chammas

## Acceptance Criterias

- [ ] Customer adds an item to shopping cart
- [ ] Customer leaves app for more shopping later
- [ ] Customer comes back to see saved items in the shopping cart

---

## Activity Diagram
[PlantUML Activity Diagram Link](https://www.plantuml.com/plantuml/duml/LOv12iCm40FlVeNUqLm2VSaIYoPWUnThy_-6q4Dw4yCmQ5NQpBEtSe_oUfzAxvomMeKZsOLqQFU8OtomNTRoqBRcec0HJ-h1SKFOg12f_y8lR9DG7gqXTqukHUbHLevwFVe2)
![Image](https://github.com/user-attachments/assets/7c6a0689-7351-4156-a7f4-721bd410e8f0)

---

## Tasks
- [ ] KYH-Net23/OrderProvider#52
  - [ ] Save cart contents to user session 
- [ ] KYH-Net23/Rika#73
  - [ ] Load saved cart items automatically when the user reopens the app and logs in.

---

## Test Case Descriptions
- [ ] Test case 1: Customer adds items to shopping cart and closes app. 
- Prerequisites:
```
1 or more items in shopping cart
```
- Steps:
```
1. Customer adds items in shopping cart
2. Customer closes the app.
3. Customer reopens app.
```
- Expected result:
```
Items is saved in cart when app reopens
```

- [ ] Test case 2: Customer adds items to shopping cart and logs out . 
- Prerequisites:
```
1 or more items in shopping cart
```
- Steps:
```
1. Customer adds items in shopping cart
2. Customer logging out.
3. Customer logging in.
```
- Expected result:
```
Items is saved in cart when customer logging in 
```
