### ISSUE TITLE
As a customer/guest, I want to be able to enter discount codes on the order details page, so that I can get the best deal

### ISSUE THREAD

**Issue by WILGROSS** [KYH-Net23/OrderProvider#6]
# Made by Mille Elfver, William Gross & Mousa Chammas

## **Acceptance Criterias**
- [ ] Customers can see the discount code field on the order details page.
- [ ] Customers can fill out a discount code.
- [ ] Customers can click “Apply promo code”.
- [ ] If promo code is valid, price is updated and a green confirmation message is shown.
- [ ] If the promo code is invalid, a red error message is shown.

---

## **Activity Diagram**
[PlantUML Link](https://www.plantuml.com/plantuml/duml/TOv1Qcin34NdNiKbesGBoU3dymT_Lahf1eIbzo9gMyRI2sJtTLwXTDAHBfTp3xfwq8YjbhI7TFwtULYLWKPtNId44PRY9h31isO9qkBejChb1oujP3W8h9vjQu5iBD26kPsdRu55fN2YniX5yuVZyBVtya0VLctd3vUa2uwltmNKSQUY_EVq53KS7-AdT7wte3A7cdTawqmXF1_wFsHIsTgYerAejHH67gZYJkjEitelz7ZoKbnmR3QLBuPyexQAen8BmhxyK_ec31d31dPN-iNLM9VaOJrTPzvg-GG0)
![Image](https://github.com/user-attachments/assets/4c7b9405-2b01-49db-a1a4-0f1615b51b88)

---

## **Tasks**
- [ ] KYH-Net23/Rika#69
> - [ ] Create a field for discount code, so customers can write freely.
- [ ] KYH-Net23/Rika#75
> - [ ] Create a button for applying a discount code, to apply the discount code.
- [ ] #9
> - [ ] Implement logic that applies the discount for selected price groups.

---

## **Test Case Descriptions**
- [ ] Test case 1: Customer applies valid discount code to order.
- **Prerequisites**
  - Customer/guest has products in the shopping cart.
- **Steps:**

   - 1. Customer is on the Order Details page.
   - 2. Customer enters a valid code in the discount field.
   - 3. Customer clicks “Apply promo code”.

- **Expected result:**
  - Green success message is displayed.
  - Total price is updated.

- [ ] Test case 2: Customer applies invalid discount code to order
- **Prerequisites**
  - Customer/guest has products in the shopping cart.
- **Steps:**

   - 1. Customer is on the Order Details page.
   - 2. Customer enters an invalid code in the discount field.
   - 3. Customer clicks “Apply discount”.

- **Expected result:**
  - Red error message is displayed.
  - No changes made to total price.
